import type {
  Speaker,
  ScheduleEvent,
  Ticket,
  User,
  EventFile,
  TicketType,
  LocationType,
  ExhibitorType,
  Poll,
  PollOption,
  UserVote,
  AppSettings,
} from "../types";

// Helper function to create ISO date strings for November 2025
const getISODateTime2025 = (day: 5 | 6, timeString: string): string => {
  const date = new Date(Date.UTC(2025, 10, day)); // Month is 0-indexed, so 10 is November
  const [time, period] = timeString.split(" ");
  let [hoursStr, minutesStr] = time.split(":");
  let hours = parseInt(hoursStr, 10);
  let minutes = parseInt(minutesStr, 10);

  if (period && period.toUpperCase() === "PM" && hours !== 12) {
    hours += 12;
  } else if (period && period.toUpperCase() === "AM" && hours === 12) {
    hours = 0;
  }
  date.setUTCHours(hours, minutes, 0, 0);
  return date.toISOString();
};

export const initialMockUsers: User[] = [
  {
    id: "user1",
    name: "Attendee User",
    email: "attendee@example.com",
    role: "attendee",
    nameIsPublic: true,
    emailIsPublic: false,
    bio: "Passionate about public health and attending the CPHVA Conference!",
    avatarUrl: "https://placehold.co/100x100.png?text=AU",
    avatarStoragePath: null,
  },
  {
    id: "admin1",
    name: "Admin User",
    email: "admin@example.com",
    role: "admin",
    nameIsPublic: true,
    emailIsPublic: true,
    bio: "Ensuring a smooth conference experience for all.",
    avatarUrl: "https://placehold.co/100x100.png?text=AD",
    avatarStoragePath: null,
  },
  {
    id: "organiser1",
    name: "Organiser User",
    email: "organiser@example.com",
    role: "organiser",
    nameIsPublic: true,
    emailIsPublic: true,
    bio: "Organising the CPHVA Annual Conference.",
    avatarUrl: "https://placehold.co/100x100.png?text=OU",
    avatarStoragePath: null,
  },
];

export const initialMockTicketTypes: TicketType[] = [
  {
    id: "tt-1",
    name: "General Admission",
    price: 75,
    description: "Access to all general sessions and exhibition hall.",
  },
  {
    id: "tt-2",
    name: "Unite Member Rate",
    price: 60,
    description: "Discounted rate for Unite members.",
  },
  {
    id: "tt-3",
    name: "Student Pass",
    price: 30,
    description: "Discounted rate for students. Valid student ID required.",
  },
];

export const initialMockLocations: LocationType[] = [
  { id: "loc-bcec-main", name: "BCEC Birmingham Main Hall" },
  { id: "loc-bcec-exhibit", name: "BCEC Birmingham Exhibition Hall" },
  { id: "loc-bcec-dining", name: "BCEC Birmingham Dining Area" },
];

export const initialMockSpeakers: Speaker[] = [
  {
    id: "speaker-jt",
    name: "Janet Taylor",
    title: "CPHVA Executive Chair",
    bio: "Executive Chair of CPHVA, leading the organisation and advocating for community public health visitors and allied professionals.",
    imageUrl: "https://placehold.co/400x400.png?text=JT",
    dataAiHint: "professional woman",
    imageStoragePath: null,
  },
  {
    id: "speaker-dh",
    name: "Dominic Hook",
    title: "National Sector Coordinator for Public Services, Unite",
    bio: "National Sector Coordinator for Public Services at Unite the Union.",
    imageUrl: "https://placehold.co/400x400.png?text=DH",
    dataAiHint: "professional man",
    imageStoragePath: null,
  },
  {
    id: "speaker-pl",
    name: "Paul Labourne",
    title: "CNO for Wales (on behalf of Sue Tranka), Welsh Government",
    bio: "Representing the Chief Nursing Officer for Wales from the Welsh Government.",
    imageUrl: "https://placehold.co/400x400.png?text=PL",
    dataAiHint: "professional person",
    imageStoragePath: null,
  },
  {
    id: "speaker-aa",
    name: "Anne Armstrong",
    title: "CNO (interim) for Scotland",
    bio: "Interim Chief Nursing Officer for Scotland.",
    imageUrl: "https://placehold.co/400x400.png?text=AA",
    dataAiHint: "professional woman",
    imageStoragePath: null,
  },
  {
    id: "speaker-sg",
    name: "Sonia Glendinning",
    title:
      "CNO for Northern Ireland (on behalf of Maria McIlGorm), Dept of Health",
    bio: "Representing the Chief Nursing Officer for Northern Ireland from the Department of Health.",
    imageUrl: "https://placehold.co/400x400.png?text=SG",
    dataAiHint: "professional woman",
    imageStoragePath: null,
  },
  {
    id: "speaker-an",
    name: "Acosia Nyanin",
    title: "CNO for England (Deputy)",
    bio: "Deputy Chief Nursing Officer for England.",
    imageUrl: "https://placehold.co/400x400.png?text=AN",
    dataAiHint: "professional woman",
    imageStoragePath: null,
  },
  {
    id: "speaker-jb",
    name: "Jo Bettison",
    title:
      "Queen's Nurse, Professional Nurse Advocate, Shropshire Community Health NHS Trust",
    bio: "Professional nurse advocate and family nurse partnership supervisor at Shropshire Community Health NHS Trust.",
    imageUrl: "https://placehold.co/400x400.png?text=JB",
    dataAiHint: "nurse smiling",
    imageStoragePath: null,
  },
  {
    id: "speaker-hb",
    name: "Helen Burke",
    title:
      "Queen's Nurse, SCPHN Lead Nurse, Derbyshire Community Health Services NHS Foundation Trust",
    bio: "SCPHN lead nurse for children and young people's mental health at Derbyshire Community Health Services NHS Foundation Trust.",
    imageUrl: "https://placehold.co/400x400.png?text=HB",
    dataAiHint: "nurse caring",
    imageStoragePath: null,
  },
  {
    id: "speaker-lg",
    name: "Lydia Gunning",
    title:
      "Programme Manager, Born in Bradford's Centre for Applied Education Research",
    bio: "Programme manager of Born in Bradford's Centre for Applied Education Research, focusing on research that impacts family health.",
    imageUrl: "https://placehold.co/400x400.png?text=LG",
    dataAiHint: "researcher woman",
    imageStoragePath: null,
  },
  {
    id: "speaker-jg",
    name: "Jenny Gilmour",
    title: "Legacy SCPHN Health Visitor",
    bio: "A legacy SCPHN health visitor and former clinical director for 0-19 services, with extensive experience in community health.",
    imageUrl: "https://placehold.co/400x400.png?text=JG",
    dataAiHint: "experienced professional",
    imageStoragePath: null,
  },
  {
    id: "speaker-nb",
    name: "Nicky Brown",
    title: "Senior Nurse and Public Health Specialist",
    bio: "Senior nurse and public health specialist with a focus on community well-being.",
    imageUrl: "https://placehold.co/400x400.png?text=NB",
    dataAiHint: "public health specialist",
    imageStoragePath: null,
  },
  {
    id: "speaker-erob",
    name: "Elaine Robinson",
    title: "Nurse Education Adviser, NMC & Northumbria University",
    bio: "Nurse education adviser for NMC professional practice, and assistant professor in the department of Nursing, Midwifery and Health at Northumbria University.",
    imageUrl: "https://placehold.co/400x400.png?text=ERob",
    dataAiHint: "educator woman",
    imageStoragePath: null,
  },
  {
    id: "speaker-hbed",
    name: "Professor Helen Bedford",
    title: "UCL Great Ormond Street Institute of Child Health",
    bio: "Professor at UCL Great Ormond Street Institute of Child Health, specializing in child health and vaccine-preventable diseases.",
    imageUrl: "https://placehold.co/400x400.png?text=HBed",
    dataAiHint: "professor academic",
    imageStoragePath: null,
  },
  {
    id: "speaker-erod",
    name: "Ethel Rodrigues",
    title: "Unite (Health) Lead Professional Officer",
    bio: "Lead professional officer for Health at Unite the Union.",
    imageUrl: "https://placehold.co/400x400.png?text=ERod",
    dataAiHint: "union officer",
    imageStoragePath: null,
  },
  {
    id: "speaker-kl",
    name: "Kitty Lamb",
    title: "CPHVA Education and Development Trust Chair",
    bio: "Chair of the CPHVA Education and Development Trust, dedicated to supporting the professional growth of health visitors.",
    imageUrl: "https://placehold.co/400x400.png?text=KL",
    dataAiHint: "chairperson woman",
    imageStoragePath: null,
  },
  {
    id: "speaker-rm",
    name: "Richard Munn",
    title: "Unite National Officer for Health",
    bio: "National officer for health at Unite the Union.",
    imageUrl: "https://placehold.co/400x400.png?text=RM",
    dataAiHint: "union officer man",
    imageStoragePath: null,
  },
  // New Speakers from Day 2
  {
    id: "speaker-jp",
    name: "Joanne Penny",
    title: "Health Visitor & Unite Representative (Wales)",
    bio: "Details for Joanne Penny.",
    imageUrl: "https://placehold.co/400x400.png?text=JP",
    dataAiHint: "professional person",
    imageStoragePath: null,
  },
  {
    id: "speaker-kp",
    name: "Kerry Parry",
    title: "Health Visitor & Unite Representative (Wales)",
    bio: "Details for Kerry Parry.",
    imageUrl: "https://placehold.co/400x400.png?text=KP",
    dataAiHint: "professional person",
    imageStoragePath: null,
  },
  {
    id: "speaker-gc",
    name: "Dr Georgia Cook",
    title: "Research Fellow, Oxford Brookes University",
    bio: "Specialism: sleep. Current focus: how school nurses can help.",
    imageUrl: "https://placehold.co/400x400.png?text=GC",
    dataAiHint: "researcher academic",
    imageStoragePath: null,
  },
  {
    id: "speaker-ft",
    name: "Dr Fiona Tierney",
    title:
      "Post-doctoral Psychology Research Assistant, Oxford Brookes University",
    bio: "Specialism: sleep. Current focus: how school nurses can help.",
    imageUrl: "https://placehold.co/400x400.png?text=FT",
    dataAiHint: "researcher academic",
    imageStoragePath: null,
  },
  {
    id: "speaker-md",
    name: "Mairead Donnelly",
    title: "PHA Nurse Consultant for Early and School Years (Northern Ireland)",
    bio: "Details for Mairead Donnelly.",
    imageUrl: "https://placehold.co/400x400.png?text=MD",
    dataAiHint: "nurse consultant",
    imageStoragePath: null,
  },
  {
    id: "speaker-ah",
    name: "Annie Hair",
    title:
      "Senior Nurse Practice Development, Glasgow and Clyde Health Board & Unite OPC Chair",
    bio: "Details for Annie Hair.",
    imageUrl: "https://placehold.co/400x400.png?text=AH",
    dataAiHint: "senior nurse",
    imageStoragePath: null,
  },
  {
    id: "speaker-khg",
    name: "Kirsty Haggerty",
    title: "Practice Development Nurse Health Visitor (Scotland)",
    bio: "Details for Kirsty Haggerty.",
    imageUrl: "https://placehold.co/400x400.png?text=KH",
    dataAiHint: "nurse health visitor",
    imageStoragePath: null,
  },
  {
    id: "speaker-af",
    name: "Amy Furness",
    title: "Midwifery Researcher, Sheffield Hallam University",
    bio: "Part of Professor Hora Soltani's team.",
    imageUrl: "https://placehold.co/400x400.png?text=AF",
    dataAiHint: "midwifery researcher",
    imageStoragePath: null,
  },
  {
    id: "speaker-hs",
    name: "Professor Hora Soltani",
    title:
      "Professor of Maternal and Infant Health, Sheffield Hallam University",
    bio: "Leading research on neonatal tests for diverse newborns.",
    imageUrl: "https://placehold.co/400x400.png?text=HS",
    dataAiHint: "professor academic",
    imageStoragePath: null,
  },
  {
    id: "speaker-dsw",
    name: "Diana Skibniewski-Woods",
    title: "Researcher on Mothers' Coping Mechanisms",
    bio: "Presenting on understanding mothers' coping mechanisms in the face of mental illness.",
    imageUrl: "https://placehold.co/400x400.png?text=DSW",
    dataAiHint: "researcher woman",
    imageStoragePath: null,
  },
  {
    id: "speaker-zr",
    name: "Zoe Rawlence",
    title: "Researcher (Cornwall)",
    bio: "Presenting on experiences of parents with learning disabilities.",
    imageUrl: "https://placehold.co/400x400.png?text=ZR",
    dataAiHint: "researcher person",
    imageStoragePath: null,
  },
  {
    id: "speaker-js",
    name: "Jo Sumner",
    title: "Researcher (Cornwall)",
    bio: "Presenting on experiences of parents with learning disabilities.",
    imageUrl: "https://placehold.co/400x400.png?text=JS",
    dataAiHint: "researcher person",
    imageStoragePath: null,
  },
  {
    id: "speaker-sa",
    name: "Sophie Ames",
    title: "Researcher (Leeds)",
    bio: "Presenting on improving uptake of childhood immunisations.",
    imageUrl: "https://placehold.co/400x400.png?text=SAmes",
    dataAiHint: "researcher woman",
    imageStoragePath: null,
  },
  {
    id: "speaker-rk",
    name: "Rukshana Kapasi",
    title: "Director of Health, Barnardo's",
    bio: "Director of health at leading children's charity Barnardo's. Working in NHS and charity for 30+ years.",
    imageUrl: "https://placehold.co/400x400.png?text=RK",
    dataAiHint: "director health",
    imageStoragePath: null,
  },
  {
    id: "speaker-sh",
    name: "Stephen Hamilton",
    title: "Psychiatric Nurse, Author, Researcher, Teacher",
    bio: "Presenting an interactive session on a health and wellbeing toolkit.",
    imageUrl: "https://placehold.co/400x400.png?text=SHam",
    dataAiHint: "psychiatric nurse",
    imageStoragePath: null,
  },
  {
    id: "speaker-cn",
    name: "Choir with No Name",
    title: "Charity Supporting Homelessness",
    bio: "An interactive performance by the Choir with No Name.",
    imageUrl: "https://placehold.co/400x400.png?text=CN",
    dataAiHint: "choir group",
    imageStoragePath: null,
  },
];

export const initialMockSchedule: ScheduleEvent[] = [
  // Day 1: Wednesday, November 5th, 2025
  {
    id: "event-day1-1",
    title: "Registration & Exhibitor Visiting",
    description: "Time for registration and to visit the exhibition hall.",
    startTime: getISODateTime2025(5, "09:00 AM"),
    endTime: getISODateTime2025(5, "09:30 AM"),
    speakerIds: [],
    locationId: "loc-bcec-exhibit",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-2",
    title: "Welcome Address",
    description: "Welcome by CPHVA Executive Chair Janet Taylor.",
    startTime: getISODateTime2025(5, "09:30 AM"),
    endTime: getISODateTime2025(5, "09:40 AM"),
    speakerIds: ["speaker-jt"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-3",
    title: "Unite Opening Address",
    description:
      "Opening address by Dominic Hook, National Sector Coordinator for Public Services, Unite.",
    startTime: getISODateTime2025(5, "09:40 AM"),
    endTime: getISODateTime2025(5, "10:00 AM"),
    speakerIds: ["speaker-dh"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-4",
    title: "PANEL: Chief Nursing Officers on CP Workforce Challenges",
    description:
      "An informative and interactive session from the UK's most senior nursing leaders, including extended Q&As with delegates.",
    startTime: getISODateTime2025(5, "10:00 AM"),
    endTime: getISODateTime2025(5, "11:00 AM"),
    speakerIds: ["speaker-pl", "speaker-aa", "speaker-sg", "speaker-an"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-5",
    title: "Refreshment Break",
    description: "Networking and exhibition viewing.",
    startTime: getISODateTime2025(5, "11:00 AM"),
    endTime: getISODateTime2025(5, "11:30 AM"),
    speakerIds: [],
    locationId: "loc-bcec-exhibit",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-6",
    title: "The Role of the Professional Nurse Advocate",
    description:
      "Enhancing Practice: Part 1. Presented by Queen's Nurse Jo Bettison.",
    startTime: getISODateTime2025(5, "11:30 AM"),
    endTime: getISODateTime2025(5, "12:00 PM"),
    speakerIds: ["speaker-jb"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-7",
    title: "The Rise of Social Prescribing",
    description:
      "Enhancing Practice: Part 2. Presented by Queen's Nurse Helen Burke.",
    startTime: getISODateTime2025(5, "12:00 PM"),
    endTime: getISODateTime2025(5, "12:30 PM"),
    speakerIds: ["speaker-hb"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-8",
    title: "Lunch Break",
    description: "Networking and exhibition viewing.",
    startTime: getISODateTime2025(5, "12:30 PM"),
    endTime: getISODateTime2025(5, "01:30 PM"),
    speakerIds: [],
    locationId: "loc-bcec-dining",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-9",
    title: "Born in Bradford",
    description:
      "Internationally recognised research project on what keeps families happy and healthy. Presented by Lydia Gunning.",
    startTime: getISODateTime2025(5, "01:30 PM"),
    endTime: getISODateTime2025(5, "02:10 PM"),
    speakerIds: ["speaker-lg"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-10",
    title: "Innovative Projects: Improving Education Infrastructure",
    description:
      "Supporting SCPHN workforce recruitment and quality post-registration teaching. Presented by Jenny Gilmour and Nicky Brown.",
    startTime: getISODateTime2025(5, "02:10 PM"),
    endTime: getISODateTime2025(5, "02:40 PM"),
    speakerIds: ["speaker-jg", "speaker-nb"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-11",
    title: "NMC Important Updates",
    description: "Presented by Elaine Robinson.",
    startTime: getISODateTime2025(5, "02:40 PM"),
    endTime: getISODateTime2025(5, "03:10 PM"),
    speakerIds: ["speaker-erob"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-12",
    title: "Refreshment Break",
    description: "Networking and exhibition viewing.",
    startTime: getISODateTime2025(5, "03:10 PM"),
    endTime: getISODateTime2025(5, "03:40 PM"),
    speakerIds: [],
    locationId: "loc-bcec-exhibit",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-13",
    title: "Vaccine Update",
    description:
      "Latest developments in vaccines. Presented by Professor Helen Bedford.",
    startTime: getISODateTime2025(5, "03:40 PM"),
    endTime: getISODateTime2025(5, "04:10 PM"),
    speakerIds: ["speaker-hbed"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-14",
    title: "Positive Culture",
    description: "Presented by Ethel Rodrigues.",
    startTime: getISODateTime2025(5, "04:10 PM"),
    endTime: getISODateTime2025(5, "04:30 PM"),
    speakerIds: ["speaker-erod"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-15",
    title: "The CPHVA Education and Development Trust Update",
    description:
      "Update on MacQueen Awards and charity work. Presented by Kitty Lamb.",
    startTime: getISODateTime2025(5, "04:30 PM"),
    endTime: getISODateTime2025(5, "04:45 PM"),
    speakerIds: ["speaker-kl"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-16",
    title: "Unite Health Update",
    description: "Presented by Richard Munn.",
    startTime: getISODateTime2025(5, "04:45 PM"),
    endTime: getISODateTime2025(5, "04:55 PM"),
    speakerIds: ["speaker-rm"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-17",
    title: "Conference Day 1 Close",
    description: "Closing remarks by CPHVA Executive Chair Janet Taylor.",
    startTime: getISODateTime2025(5, "05:00 PM"),
    endTime: getISODateTime2025(5, "05:15 PM"),
    speakerIds: ["speaker-jt"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day1-18",
    title: "Unite-CPHVA Excellence Awards Presentation and Dinner Buffet",
    description: "Awards presentation (starts 7:30 PM) and networking dinner.",
    startTime: getISODateTime2025(5, "07:00 PM"),
    endTime: getISODateTime2025(5, "10:00 PM"),
    speakerIds: [],
    locationId: "loc-bcec-dining",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },

  // Day 2: Thursday, November 6th, 2025
  {
    id: "event-day2-1",
    title: "Registration & Exhibitor Visiting (Day 2)",
    description: "Time for registration and to visit the exhibition hall.",
    startTime: getISODateTime2025(6, "08:40 AM"),
    endTime: getISODateTime2025(6, "09:00 AM"),
    speakerIds: [],
    locationId: "loc-bcec-exhibit",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day2-2",
    title: "Welcome (Day 2)",
    description: "Welcome by CPHVA Executive Chair Janet Taylor.",
    startTime: getISODateTime2025(6, "09:00 AM"),
    endTime: getISODateTime2025(6, "09:10 AM"),
    speakerIds: ["speaker-jt"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day2-3",
    title: "PANEL: Pressing issues facing clients across the UK",
    description:
      "Senior practitioners and academics share insights on challenges and opportunities facing families. (Including extended Q&As with delegates)",
    startTime: getISODateTime2025(6, "09:10 AM"),
    endTime: getISODateTime2025(6, "10:20 AM"),
    speakerIds: [
      "speaker-jp",
      "speaker-kp",
      "speaker-gc",
      "speaker-ft",
      "speaker-md",
      "speaker-ah",
      "speaker-khg",
    ],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day2-4",
    title: "Innovative projects 2: Neonatal tests for diverse newborns",
    description:
      "Research and practice updates on neonatal tests for Black, Asian and ethnic minority newborns.",
    startTime: getISODateTime2025(6, "10:20 AM"),
    endTime: getISODateTime2025(6, "11:00 AM"),
    speakerIds: ["speaker-af", "speaker-hs"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day2-5",
    title: "Refreshment Break (Day 2)",
    description: "Networking and exhibition viewing.",
    startTime: getISODateTime2025(6, "11:00 AM"),
    endTime: getISODateTime2025(6, "11:30 AM"),
    speakerIds: [],
    locationId: "loc-bcec-exhibit",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day2-6",
    title: "CALL FOR PAPERS presentations",
    description:
      "Celebrating Innovation in Practice: Successful submissions are presented to delegates. Includes: Understanding mothers' coping mechanisms (Diana Skibniewski-Woods), Experiences of parents with learning disabilities (Zoe Rawlence; Jo Sumner), Developing research capacity of SCPHNs (O-19 Research Network), Improving uptake of childhood immunisations (Sophie Ames).",
    startTime: getISODateTime2025(6, "11:30 AM"),
    endTime: getISODateTime2025(6, "12:45 PM"),
    speakerIds: ["speaker-dsw", "speaker-zr", "speaker-js", "speaker-sa"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day2-7",
    title: "Lunch Break (Day 2)",
    description: "Networking and exhibition viewing.",
    startTime: getISODateTime2025(6, "12:45 PM"),
    endTime: getISODateTime2025(6, "01:45 PM"),
    speakerIds: [],
    locationId: "loc-bcec-dining",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day2-8",
    title: "Nick Robin Memorial Lecture/ Keynote speaker",
    description:
      "Rukshana Kapasi, Director of health at Barnardo's, will discuss major new projects and the need for more co-ordinated services due to workforce issues.",
    startTime: getISODateTime2025(6, "01:45 PM"),
    endTime: getISODateTime2025(6, "02:30 PM"),
    speakerIds: ["speaker-rk"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day2-9",
    title: "Looking after number one",
    description:
      "Health and wellbeing toolkit to improve practitioner mental health. Interactive session with Stephen Hamilton.",
    startTime: getISODateTime2025(6, "02:30 PM"),
    endTime: getISODateTime2025(6, "03:20 PM"),
    speakerIds: ["speaker-sh"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day2-10",
    title: "A special finale to celebrate the professions",
    description:
      "An interactive performance by the Choir with No Name, a charity supporting those affected by homelessness.",
    startTime: getISODateTime2025(6, "03:20 PM"),
    endTime: getISODateTime2025(6, "03:35 PM"),
    speakerIds: ["speaker-cn"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "event-day2-11",
    title: "Conference Close",
    description: "Closing remarks by CPHVA Executive Chair Janet Taylor.",
    startTime: getISODateTime2025(6, "03:45 PM"),
    endTime: getISODateTime2025(6, "04:00 PM"),
    speakerIds: ["speaker-jt"],
    locationId: "loc-bcec-main",
    offerDownloads: false,
    eventFiles: [],
    createdAt: new Date().toISOString(),
  },
];

export const initialMockTickets: Ticket[] = [
  {
    id: "ticket-admin1-gen",
    userId: "admin1",
    userName: "Admin User",
    conferenceName: "Unite-CPHVA Annual Professional Conference 2025",
    ticketType: "General Admission",
    ticketPrice: 75,
    purchaseDate: new Date(2025, 9, 1).toISOString(),
    qrCodeValue: "ADMIN1-TICKET1-CPHVA2025-GENERAL",
    isCheckedIn: false,
    checkInTimestamp: null,
  },
  {
    id: "ticket-user1-gen",
    userId: "user1",
    userName: "Attendee User",
    conferenceName: "Unite-CPHVA Annual Professional Conference 2025",
    ticketType: "Unite Member Rate",
    ticketPrice: 60,
    purchaseDate: new Date(2025, 9, 2).toISOString(),
    qrCodeValue: "USER1-TICKET1-CPHVA2025-UNITE",
    isCheckedIn: false,
    checkInTimestamp: null,
  },
];

export const initialMockExhibitors: ExhibitorType[] = [
  {
    id: "ex-1",
    name: "Public Health Solutions Ltd.",
    description:
      "Providing innovative solutions for public health challenges. Visit our booth for demos and consultations.",
    logoUrl: "https://placehold.co/400x225.png?text=PHS",
    logoStoragePath: null,
    dataAiHint: "health company",
    websiteUrl: "https://example.com/phs",
    boothNumber: "C102",
  },
  {
    id: "ex-2",
    name: "Community Care Tech",
    description:
      "Technology empowering community health workers and improving patient outcomes.",
    logoUrl: "https://placehold.co/400x225.png?text=CCT",
    logoStoragePath: null,
    dataAiHint: "tech community",
    websiteUrl: "https://example.com/cct",
    boothNumber: "D201",
  },
];

export const initialMockPolls: Poll[] = [
  {
    id: "poll-nov25-1",
    question: "Which session are you most looking forward to on Day 1?",
    options: [
      { id: "optA1", text: "PANEL: Chief Nursing Officers", votes: 0 },
      { id: "optA2", text: "Born in Bradford", votes: 0 },
      { id: "optA3", text: "Vaccine Update", votes: 0 },
    ],
    isOpen: true,
    createdAt: getISODateTime2025(5, "08:00 AM"),
  },
];

export const initialMockUserVotes: UserVote[] = [];

export const defaultAppSettings: AppSettings = {
  title: "Unite-CPHVA Annual Professional Conference 2025",
  ticketSalesEnabled: true,
  colors: {
    background: "0 0% 94%",
    foreground: "0 0% 20%",
    primary: "166 29% 40%", // Teal #498375
    accent: "283 49% 60%", // Vibrant Purple #BA68C8
  },
};
